name: ecommerce_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  build_runner: ^2.4.11
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.2.0
  http: ^1.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializer: ^0.2.0
  json_serializable: ^6.8.0
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
